### ISSUE TITLE
Upgrade to Node v0.12.2

### ISSUE THREAD

**Issue by TheNando** [rackerlabs/encore-ui#1069]
The earliest version of Node supported by the framework, as listed in the package.json dependancies, is v0.8. This version was released on June 25, 2012. Considering that the earliest version of the framework was released on Jan 15, 2014, Node v0.8 is an old version by reasonable standards. It's also worth note that the framework currently does not build in this version as the built-in npm certificates for this version have expired. The earliest version supported in the framework's current state is determined by the following dependency:

`imagemin  node >= 0.10.0 npm >= 2.1.5`

While very little has been deprecated since Node v0.8, many useful features have been added. Specifically of use are the sync versions of some functions, such as execSync added in v0.11.12, which allows for more flexibility in the grunt build process.

Node v0.12.2 has been out since March 31, 2015 and is a good candidate for upgrade.

The following project correctly build locally using Node v.12.2:
* encore-ui
* supportservice-ui
* billing-ui
* account-ui
* vcenter-ui

**Comment by parlarjb** [comment]
@halkon @nickburns2006 Is Ticketing ok with this? I know Freddy says that he uses a new version locally, so I'd _assume_ everything is alright.

**Comment by parlarjb** [comment]
@jj4th @CITguy Do you know if Cloud would be ok with this?

**Comment by halkon** [comment]
I am ok with it, and we'll just have to deal with updating the dependency stack as needed, that being said I am using node version `0.12.2` and things have been good with ticketing. 

That being said I do want to at least post this, where I found an issue when upgrading node to this version was, as @TheNando mentioned, `execSync`, where we were using the `execSync` package and not the native functions introduced in node. 

Due to me being on the latest and @nickburns2006 and @solim8r on the earlier version of node, I ended up having to wrap the `execSync` calls:

```javascript
var exec = function () {
    // See if we are using node 0.12 otherwise attempt to get `execSync` execution
    // https://npmjs.org/package/execSync
    // Executes shell commands synchronously

    var commandResult;
    if (require('child_process').exec) {
      commandResult = require('child_process').exec.apply(null, arguments);
    } else {
      commandResult = require('execSync').exec.apply(null, arguments).stdout;
    }
    return commandResult;
};
var sh = function () {
    // See if we are using node 0.12 otherwise attempt to get `execSync` execution
    // https://npmjs.org/package/execSync
    // Executes shell commands synchronously

    var commandResult;
    if (require('child_process').execSync) {
      commandResult = require('child_process').execSync.apply(null, arguments);
    } else {
      commandResult = require('execSync').run.apply(null, arguments).stdout;
    }
    return commandResult;
};


// GRUNT-GITHOOKS START
// var sh = require('execSync').run;

var shOutput = exec; //require('execSync').exec;
var file, command, fileChanged;
```

Ignoring the naming conventions, that was the best way to co-exist with both versions of node.  I post it mainly as a way for other projects to see if they need to implement this until everyone is fully over. 

Also, this means that the `builder` and `test` nodes have to all be upgraded which will be perhaps a bigger feat while each project upgrades to this version. 

The test nodes are currently on version `0.10.28`, and `yum` reports version `0.10.36` as the most recent available version of the package. (Not sure if this is somehow anchored by `semver` but if I remember correctly, `yum` is always behind, so we might have to add a separate repo for latest node)

So to upgrade we might have to manually compile it...

**Comment by halkon** [comment]
Actually just found this: 

https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories

**Comment by CITguy** [comment]
I've not had any problems running node v0.12.2 on my machine with Cloud UI.  To my knowledge, it shouldn't be an issue, but @jj4th may know things I don't.

**Comment by halkon** [comment]
I don't see a real issue of moving to it and we can just deal with the exceptions, the main issue/possibility would be people not upgrading their machines. 

Also something @TheNando and I spoke about was, perhaps the good starting point is start upgrading all the dependencies we have, and seeing what is needed or not after upgrading to `0.12.X`, from there we can drive the "We no longer support earlier versions of node"

Thoughts?

**Comment by CITguy** [comment]
Closing. Captured in JIRA https://jira.rax.io/browse/FRMW-72
