### ISSUE TITLE
layout-wrap does not cause the flex-box to actually wrap

### ISSUE THREAD

**Issue by jonkruse00** [rackerlabs/encore-ui#1180]
I noticed this while i was trying to cause a wrap in my own code but also noticed it on the framework documentation (below image) 
<img width="377" alt="screen shot 2015-09-08 at 11 16 03 am" src="https://cloud.githubusercontent.com/assets/5339195/9740578/22525fba-561b-11e5-9ed0-fee65fbf8fcf.png">

**Comment by CITguy** [comment]
Speaking with @jonkruse00, this is expected behaviour from the framework, but it is not the behaviour required for development. 

The desired outcome is to be able to apply attribute values to two flex children, so that:

1. with enough horizontal space, the children should sit side by side (each taking a portion of the parent width)
2. when horizontal space is constrained, the first child should sit above the second (each consuming full width of the parent)

The `flex="NN"` attributes use percentage values with no grow/shrink capabilities, so this only satisfies the first requirement.  To satisfy the second requirement, it would require having mixed types of flex children (one "static", one "dynamic") *without* percentage `flex-basis` values.  However, coding support for all possible values would be near impossible.  Instead, I recommend documenting this impediment and provide some basic support for defining custom CSS to achieve the desired behaviour.

**Comment by TheNando** [comment]
The flex module we use has a solution for this. You have to include the responsive version of the css and specify the size suffix for your elements. 

You can find the size breakdowns in the vars.less file
```

/*
 * Layouts Module
 *
 * Sizes:
 *  0    <= size < 600     Phone
 *  600  <= size < 960     Tablet
 *  960  <= size < 1200    Tablet-Landscape
 *  1200 <= size           PC
 */
@layout-gutter-width:      16px;
@layout-breakpoint-sm:     600px;
@layout-breakpoint-md:     960px;
@layout-breakpoint-lg:     1200px;
```

So, say you have div1 and div2. On a screen less than 600px, they should each get their own row, otherwise, they should share a row.

```
<div id="div1" flex="50" flex-sm"100"></div>
<div id="div2" flex="50" flex-sm"100"></div>
```

That's off the top of my head, so I'm not _positive_ that's the syntax. But the attributes are there.

https://github.com/rackerlabs/encore-ui/blob/master/src/layout/responsive.less

**Comment by glynnis** [comment]
Sounds like from @TheNando's comment that this has a fix. Closing.

@CITguy @jonkruse00 If this issue is still relevant, please reopen.
