### ISSUE TITLE
Datepicker Z-Index modal issue

### ISSUE THREAD

**Issue by vlutton** [rackerlabs/encore-ui#1694]
Encore-UI-Version: 1.47.2
When the datepicker is used on a modal and its lower on the body of the modal, it gets hidden behind the modal footer.  I have attached a screenshot with an example of this occurring.

<img width="340" alt="datepicker-z-index-issue" src="https://cloud.githubusercontent.com/assets/1016008/15723140/c0cf4140-2806-11e6-8b43-6d35cff04976.png">

**Comment by Droogans** [comment]
Would you want this to block the Submit/Cancel button?

**Comment by vlutton** [comment]
I would think so, you are still in the process of populating the form at that point before attempting to submit it and it auto-collapses on select.

**Comment by 100stacks** [comment]
@vlutton, all great points.  We would need design perspective/feedback on this behavior as it would apply across `EncoreUI`.

cc/ @glynnis

**Comment by glynnis** [comment]
Yes, date pickers should appear over modal buttons (or other buttons), as anything appearing in front of the date picker might prevent the user from selecting the date of their choice.

**Comment by CITguy** [comment]
Captured in https://jira.rax.io/browse/FRMW-914

**Comment by kevincareer427** [comment]
@CITguy helped me with this

Actually it's behaving as it's expected. The picker is in front of the modal content (which scrolls), but the footer is fixed and is not in the same stacking context. Unless we want to put the footer at the bottom of the scrolling content (which does not guarantee the footer is always visible), there's not much we can do.

@glynnis Please advise. Would we want to put the footer at the bottom of the scrolling content?

## modal open picker closed
<img width="586" alt="11" src="https://cloud.githubusercontent.com/assets/18704680/16092805/e92c5e54-32fe-11e6-8179-cd250d8e5c2c.png">

## modal open picker open
<img width="581" alt="22" src="https://cloud.githubusercontent.com/assets/18704680/16092825/fd5075c8-32fe-11e6-9927-634d8dc88f0d.png">

## modal open picker open scrolled
<img width="589" alt="33" src="https://cloud.githubusercontent.com/assets/18704680/16092839/077466f4-32ff-11e6-951d-a8d346c8d506.png">

**Comment by CITguy** [comment]
It just occurred to me that this would also be an issue with `rxMultiSelect` as well.

**Comment by glynnis** [comment]
@kevincareer427 and I just chatted about this, and it's important that the footer is always visible/the user doesn't have to scroll in order to see the footer.

For that reason, the best solution for now (unless we refactor our modals and fix stacking context, which I think is out of scope for now) is to, as @kevincareer427 showed, add enough space below the DatePicker when it is clicked so that the user can scroll and see all of it, and keep the modal footers as they currently are--always visible.

Let me know if there's any need for additional clarification.

**Comment by kevincareer427** [comment]
@glynnis Thanks for the clarification Glynnnis. I'll let you know once Ryan and I figure out how to solve this problem.

**Comment by CITguy** [comment]
Due to a perfect storm combination of z-index, overflow, and relative/absolute positioning with regards to modal windows, there's no solution that will allow us to keep the content scrollable in a modal window. However, if we remove the scrolling functionality, everything works perfectly... see below.

This does change behavior of modal windows, because the modal will then grow vertically to fit content.

@glynnis: what do you want to do?

### BEFORE
![modal-before](https://cloud.githubusercontent.com/assets/545605/16208206/a8332134-36f6-11e6-9f30-53e3289a90f4.png)

![screen shot 2016-06-20 at 2 53 30 pm](https://cloud.githubusercontent.com/assets/545605/16208239/cfc96bb8-36f6-11e6-844f-13d9b326284a.png)


### AFTER
![modal-after](https://cloud.githubusercontent.com/assets/545605/16208210/acd9b96e-36f6-11e6-8975-3d6d7b2a02d3.png)

![modal-after-control-open](https://cloud.githubusercontent.com/assets/545605/16208209/accd217c-36f6-11e6-8ea7-df21619109f9.png)

**Comment by CITguy** [comment]
Long story short...

![css](http://i.imgur.com/OuwqI4y.gif)

**Comment by glynnis** [comment]
@CITguy @kevincareer427 and I met about this to discuss the options they presented. We determined:
* Turning scrolling off and growing the height of the modal isn't a good solution, given that some modals already exist that rely on scrolling and their height may be too large for smaller screens. Overall the scrolling functionality of a modal is desirable, so we don't want to change it.
* The best option (since none are really ideal...) is to create a helper class that creates extra bottom margin and/or padding. This helper class can be applied to elements like rxDatePicker fields, multiselect dropdowns, etc. that run into this problem when they're at the bottom of a modal. The extra margin/padding won't make those elements appear on top (due to all the z-index/stacking context issues discussed above), but it will give users the ability to scroll down to see the full height of that element.

We will get a helper class added that accommodates the height of each element that encounters that issue, as well as recommend strongly that developers avoid putting those elements at the bottom of a modal if it's avoidable.

**Comment by 100stacks** [comment]
@vlutton: @CITguy pushed PR https://github.com/rackerlabs/encore-ui/pull/1737 if you're interested in the solution.

**Comment by CITguy** [comment]
This should be fixed in Wednesday's release (`encore-ui 2.1.0`)

**Comment by CITguy** [comment]
Fixed in 2.1.0
