### ISSUE TITLE
Reduce 'near duplicate' colors via CSS-Colorguard

### ISSUE THREAD

**Issue by klamping** [rackerlabs/encore-ui#384]
Using https://github.com/SlexAxton/css-colorguard, combine the colors that are pretty much the same (e.g. #000000 and #020202).

**Comment by CITguy** [comment]
@glynnis, is this still a valid issue? Is this related to #792?

**Comment by glynnis** [comment]
@CITguy Yes, still valid. I think both this issue and #792 are tied up in an underlying need to centralize and de-dup CSS and styles (since most near-match colors are results of CSS/styles being applied at a project level). So maybe this issue and/or #792 can serve as a technical spike for now to investigate level of effort to run this across all projects/pages in Encore and report back?

Even before we look at the bigger issue of de-dup and centralizing CSS, I think it would be useful just to have the data of all colors used (and where), just to understand the scope of the problem. We can chat more in Slack about it (also #visual-guardians) if that doesn't give you the proper constraints you need to look at this :smile:

**Comment by CITguy** [comment]
Closing. Captured in JIRA https://jira.rax.io/browse/FRMW-78
