### ISSUE TITLE
Bulk select/deselect with actions

### ISSUE THREAD

**Issue by parlarjb** [rackerlabs/encore-ui#703]
We need a way to do bulk selects and deselects on table rows. We will also need to run actions on bulk selected items.

See 

 * https://jira.rax.io/browse/UXENCORE-28 (which includes links to mockups)
 * https://jira.rax.io/browse/UXENCORE-30

**Comment by megalord** [comment]
After looking through the existing implementation, one thing that I think will need some change is `rxTableFilter`, which basically controls an entire row in the table head and doesn't allow for other content.  Also, does hiding the Batch Actions link conflict with the sentiment expressed in issues #837 and #908?  I personally like the disabled approach more than hiding the link.

@parlarjb @glynnis Is there some room to make minor changes like this?

**Comment by parlarjb** [comment]
`rxTableFilter` can complete go. It was a placeholder, and now that `rxSearchBox` is a real thing, you should use that instead.

I'll let @glynnis speak to the batch actions link. There's room for whatever change we feel is necessary, but for design stuff, I want the final word to be from her.

Note: @glynnis and I are both off on Monday, and I don't check email on weekends :)

**Comment by glynnis** [comment]
@megalord Got this in front of our design team, and the decision is: always show the Batch Actions link, but disable it (style + function) if nothing is selected. If it's disabled and the user hovers over the Batch Actions link, we should display a tooltip with something like, "You must select at least two items to use batch actions."

@nancyAfox Can you be sure a story gets created for the Cloud backlog so that once this work is completed/merged into the Framework, someone refactors Cloud? We'll need a developer to ensure all the Framework code is being drawn on (rather than code/styles/etc. persisting/overriding at the Cloud project level). Happy to help if you have questions. cc/ @lfielder

**Comment by nancyAfox** [comment]
@glynnis Jira story created for Encore Cloud:  https://jira.rax.io/browse/EN-2088
