### ISSUE TITLE
Assign priority to statuses across Encore so that sorting by status is a better UX

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#737]
See https://github.com/rackerlabs/encore-ui/pull/735/files#r22968116

**Comment by parlarjb** [comment]
One thing we could do is allow devs to pass in the desired ordering, much like they pass in the mapping, rather than forcing them to write a sorting function each time. They're already telling us "map BLOCKED, SHUTDOWN and FAILED to the ERROR status", we could also let them say "The sort ordering should be `["SHUTDOWN", "BLOCKED", "FAILED"]`

**Comment by halkon** [comment]
Would that allow for saying something like 

I want: `['ACTIVE', 'SHUTDOWN']` to be sorted first and let the rest of the statuses sort alphabetically?

**Comment by halkon** [comment]
(which :+1: for the list, that's an excellent solution)

**Comment by glynnis** [comment]
@CITguy @halkon @parlarjb Has this already been done?

**Comment by halkon** [comment]
This has not been implemented

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-458
