### ISSUE TITLE
rxForm/rxModalForm - request for background grey input boxes for disabled.

### ISSUE THREAD

**Issue by dman777** [rackerlabs/encore-ui#758]
This is a feature request, please, to have the input boxes background color to be grey when html has disabled attribute. This example is from using `rx-modal-form`

```html
    <rx-form-item label="I'm disabled but my input box is white">
      <input type="text" id="label" name="label" ng-model="foo.bar" disabled />
    </rx-form-item>
```

**Comment by CITguy** [comment]
Would this be applicable to any form element, regardless of DOM hierarchy?

**Comment by dman777** [comment]
Yes, I think that would be best in my opinion.

**Comment by CITguy** [comment]
@glynnis, any comments/concerns?

**Comment by glynnis** [comment]
@CITguy I'll need to take some time to consider design (colors, mouse interaction, etc.), and also whether we could use this on other form elements (select boxes, etc.), though the latter could probably exist as a different issue.

I'll take some time to look into this and get mock-ups (if needed -- might not be), but have a few other higher priority things on my plate at the moment. Hoping I can get to this in the next few days, though.

**Comment by glynnis** [comment]
Would it be a "nice to have" or a requirement for the disabled state to allow for text entered in the input box? (i.e. there's text already in the input but you can't interact with it)?

**Comment by dman777** [comment]
Yes, please....we would need to be able to show pre-populated text in the disabled boxes. With LBS, we pre-populate the input boxes with information that already exists and grey it out letting the user know they can not modify it. 

A perfect example would be boostrap's `Disabled state`. This is what we were using before for this effect(angular-ui fork of it rather):
![pic](https://cloud.githubusercontent.com/assets/887815/5975791/24306a3a-a84b-11e4-99b1-310a0ccf4d0a.jpg)

**Comment by megalord** [comment]
Circling back since this was mentioned in the stakeholders meeting today...

It is worth noting that we also have a need for disabled select boxes.  This will require some extra effort because the select boxes have an arrow that is styled using the `before` and `after` pseudo-elements.  However, these attributes are applied to the `span.field-select`, and the `select` element does not support them.

**Comment by glynnis** [comment]
I've got a PR up for input/text boxes only here: https://github.com/rackerlabs/encore-ui/pull/859

I looked into also applying styles to the select boxes, but I'm going to need some help/additional perspective. Perhaps my CSS-fu is a bit weak on a Friday afternoon, or perhaps this is legit complex -- not sure which is the case here :stuck_out_tongue: 

Here's the problem from a CSS perspective: styling input boxes is easy. Here's their markup:
```
<input name="ipaddress" type="text" ng-model="test" placeholder="127.0.0.1" disabled class="ng-scope ng-pristine ng-valid" id="field-099">
```

The presence of `disabled` means we can write CSS styles for the input (as I did in my PR) using:
```
input {
    &[disabled] {
        color: #999;
        background-color: #dededd;
        cursor: not-allowed;
    }
}
```

However, for select boxes, the dropdown arrow has a background and caret which are drawn through the use of `before` and `after` on `.field-select`, which is a wrapper for `select`. `select` is the element that gets `disabled`, but the `before`/`after` pseudo-elements that style the arrow color are on the `select`'s parent element, and thus cannot be styled using the same pattern of inheritance in LESS. This is perhaps demonstrated better via mark-up:

```
<rx-form-item label="Type" description="Bound Value: SATA" class="ng-isolate-scope">
    <div class="form-item" ng-class="{'text-area-label': isTextArea}">
        <div class="field-content">
            <span class="field-input-wrapper" ng-transclude="">
                <span class="field-select ng-scope">
                    ::before
                    <span class="field-input">
                        <select ng-model="volume.type" ng-required="true" disabled="" class="ng-pristine ng-valid ng-valid-required" id="field-09D" required="required">
                        ...
                        </select>
                    </span>
                    ::after
                </span>
            </span>
        </div>
    </div>
</rx-form-item>
```

So here, `before` and `after` are tied to the parent element, which does not have `disabled` (and thus doesn't allow for us to change styles of the arrow). 

Does anyone have ideas on how we can approach this so that we can style the arrow without fundamentally changing the way we're constructing select boxes/styles? Last time we changed those styles it was kind of a headache, and I feel confident that we're in a good spot with them (especially re: cross-compatibility in browsers) so I'd prefer to leave them alone if we can.

**Comment by CITguy** [comment]
@glynnis, I've been toying around with this in my spare time. Check out how the select boxes are styled at http://jsbin.com/qurixa/12

#### Wrapping the Native Element
I'm not performing some convoluted `content` css hack. I'm merely removing some built in styles and placing a layer in front of the native element with a custom "button" that I can style however I want.

#### Styling the Native Element (as best as possible)
Because there's no single way to get rid of the native dropdown button, I apply best effort CSS to remove it in the majority of cases. My custom "button" sits in front of the native button in cases where it still displays (because Firefox... :anger:), essentially hiding it from view.

#### Interacting with the Native Element
Now, here's the trick. My custom "button" is currently sitting in front of the `<select>`, so mouse events don't pass through to the native element.  Have no fear! Using the `pointer-events: none !important;` CSS rule will send all pointer events _through_ the custom button to the native `<select>` allowing me to interact directly with the native element.

#### Benefits
* It works in Firefox, Chrome, and Safari
* User interacting with the native `<select>` element.
* 100% CSS Styling
* "button" icon can be defined directly in the HTML markup. (no need for CSS `content` rule hacks)
* With the use of the `rxSelect` directive to add the required markup around `<select>` elements, this can be implemented in existing apps with very little effort.

**Comment by glynnis** [comment]
@CITguy Excellent! Do you think you could make a PR? One thing I know we'll have to look at in changing this in the Framework is the custom colors/width for the left nav user drop down. 

Otherwise this is just a CSS change and not a breaking change, correct?

**Comment by CITguy** [comment]
Sure, I'll get a PR submitted soon.

The CSS in my example requires certain markup to be present around the `<select>`. The `rxSelect` directive in the same example takes care of wrapping the `<select>` with the required markup. I could say more, but I'll leave it for the PR discussion.

**Comment by glynnis** [comment]
:+1: Thanks for looking into this!

**Comment by glynnis** [comment]
Changing assignee to @CITguy since he'll be working on the `<select>` stuff discussed above.

**Comment by CITguy** [comment]
Closing - disabled text box styles already in production releases (See #859).  Separate issue in place for styleable `<select>` elements (See #896).
