### ISSUE TITLE
Allow step transition in wizard-style rxModal windows.

### ISSUE THREAD

**Issue by eric-dunham** [rackerlabs/encore-ui#825]
The new implementation of multi-screen/wizard-like modals does allow a user to return to a previous step to correct an error or review a previous page. The user must cancel out of the entire dialog.

**Comment by parlarjb** [comment]
There shouldn't be anything stopping you from doing this as-is. All the new implementation really adds is the ability to specify your own set of custom buttons to be used. It's up to you to define what the buttons do. You can have "Back", "Forward" and "Cancel" buttons.

That said, this isn't a full wizard-like implementation, because it doesn't automate the state transitions.

cc @megalord

**Comment by megalord** [comment]
That's right.  The `rxModalAction` used to exercise strict control over the footer content, but now there is a way to define custom footers.  The body of the modal is still in (almost) full control of the developer.  In order to do step transitions, the `scope.setState()` method could be used in the `ng-click` handlers of the footers you define.  The new example in the docs has a footer that uses this methodology to return to a previous screen.

**Comment by parlarjb** [comment]
I'm going to close this issue. We'll re-open if we find in practice that we need more built-in functionality
