### ISSUE TITLE
Use HTML template for rxCharacterCount markup

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/encore-ui#839]
`rxCharacterCount` has begun to gather a bit of markup in the javascript and should be refactored to use an HTML template for markup.

This can be achieved using `transclude: 'element'` along with `replace: true` to ensure that the form element (be it input or textarea) itself is inserted into the template and not their contents (if applicable).

**Comment by CITguy** [comment]
This relates to #835 

@parlarjb mentioned [this nugget](http://ng.malsup.com/#!/transclude-property) around ngTransclude, but had concerns that `replace: true` is deprecated.  However, according to [this angular documentation](https://docs.angularjs.org/api/ng/service/$compile), `replace` will be removed with angular 2.0.  At that point, the directive would need a rewrite anyway, so I do not believe that this would stop us from using the `replace` DDO property.

**Comment by megalord** [comment]
I actually looked into this a bit.  The problem with `replace: true` is that *all* the attributes are copied to root element of the template. So you end up with
```html
<div rows="10" cols="50" ng-model="fields.comment" ... >
```
The duplication of the `ng-model` attribute will actually prevent the binding from being applied to the input.  Also, I don't like the idea of assigning irrelevant attributes like `rows` or `type="text"`, and I am hesitant to implement a screening attributes, since that doesn't seem like much of an improvement over what we have now.

**Comment by glynnis** [comment]
Looks like we might need an epic for changes/improvements to rxCharacterCount cc/ @CITguy

**Comment by CITguy** [comment]
Yes, I agree. The component is very experimental and could benefit from some design TLC.

**Comment by anur2213** [comment]
Associated Jira story: https://jira.rax.io/browse/FRMW-528
