### ISSUE TITLE
rxFormItem textarea z-index: 2?

### ISSUE THREAD

**Issue by halkon** [rackerlabs/encore-ui#900]
https://github.com/rackerlabs/encore-ui/blob/master/src/rxForm/rxForm.less#L98

Looks like `textarea` is getting a `z-index` of 2.  Something that's likely not needed.  Would like to discuss with @glynnis @parlarjb @CITguy before proposing a fix to the framework.

**Comment by CITguy** [comment]
Could this have something to do with rxCharacterCount styling?

**Comment by megalord** [comment]
FYI, I remember having to adjust the z-index of the [typeahead](https://github.com/rackerlabs/encore-ui/blob/master/src/typeahead/typeahead.less#L13) so that it rendered on top of `textarea`s.  You may also want to make a change there.  `git blame` shows the `z-index` for `textarea` was set last August, so I doubt it's related to `rx-character-count`.

**Comment by parlarjb** [comment]
This was brought in my @nickburns2006 when he added the "compressed layout" styles.

**Comment by halkon** [comment]
This was brought in a few months (4 to be exact) shy off a year ago.  I don't think it would mess anything up if we removed it, just seems unnecessary (and caused some issue with the `ui-bootstrap` typeahead plugin.

**Comment by halkon** [comment]
And I just totally read @megalord 's comment.  Either way, it's old, and most likely unnecessary.

**Comment by CITguy** [comment]
This issue is in regards to the compressed layout for current form styles. Considering that there is no such thing as "compressed" forms in the upcoming rxForm rework, I'm going to mark this as "won't fix" and close the issue.
