### ISSUE TITLE
Re-evaluate the usage of description lists <dl> for metadata

### ISSUE THREAD

**Issue by TheNando** [rackerlabs/encore-ui#939]
The metadata component is one of the most commonly and inconsistently used in Encore apps. Often, the styling is overwritten to change its default behavior. Commonly overwritten properties include: text-align, min-width, margin, clear.

Furthermore, clearing and floating elements becomes problematic when mixed with other inconsistently implemented app elements. In its current state, metadata will not play well with responsive layout attributes. It would be prudent to re-evaluate the intended design of this component and determine if a more appropriate html element should be used instead of dl or if it is a good candidate to make use of the flex module.
 
Examples of how metadata is being inconsistently used can be seen in Account Overview (right aligned dt), Billing Overview (left aligned dt), Billing Current Usage tab, and Support Details (right aligned but misaligned for some reason).

**Comment by megalord** [comment]
Definitely related to #885

**Comment by glynnis** [comment]
Marked this "Needs Design" and "on hold" to indicate that metadata is currently being worked on by design, so any dev work here should wait until we deliver mock-ups (though we do, indeed, want to address the `<dl>` issues, we should just hold off 'til more of the visual/design side of things is ready to discuss).
