### ISSUE TITLE
Striped table styling for multiple alternate rows

### ISSUE THREAD

**Issue by scadams** [rackerlabs/encore-ui#986]
Currently, the table-striped styling works for alternate rows where one row represents a single entry, but not if multiple rows are needed to represent a single entry.

The subtables in the following example show progress bars that go with the job entry above them:
![notifications_redesign](https://cloud.githubusercontent.com/assets/753260/7822419/fc361342-03ba-11e5-9006-b4923655bcbd.png)

**Comment by ElementE** [comment]
![mass-ticketing-sub-child-rows](https://cloud.githubusercontent.com/assets/7989545/7824611/e875bd9e-03c9-11e5-8d3c-5f3a3b4c55ff.png)

**Comment by ElementE** [comment]
@scadams 
So really I think the issue here is pretty unique to your use-case (in-terms of what the Encore pattern library has standardized), since you need to see child rows of a parent and give them some sort of visual contrast. Ideally you could have your just your data-rows striped  and then leave the progress area white (or vice versa). Then also adding bottom padding to distinguish the next row start. This helps clearly delineate each value-set inside the sub-area at a glance. 

Just a stab, I wanted to play with this issue and see what you thought. Lets bounce ideas back and forth here a bit!

**Comment by kobowley** [comment]
@scadams.@elementE  We spoke with scott Imel and we agreed that as far as priority is concerned getting Flashmob up to Encore pattern library will come after the CORE ticket Flash mob goes out. From my perspective we can wait on the Design LGTM until after the CORE tickets release goes out.

**Comment by scadams** [comment]
@kobowley The reason I worked on this was because I had some time to throw at this while another developer was finishing up the remaining CORE work and we are waiting on a deployment and testing. I figured this page, the landing page, was the biggest eyesore in terms of Encore UI compliance, so I wanted to knock it out while I had a chance.

@ElementE I actually really like what you did with the design - it's a simple change, though I will have to do my own styling if I understood you correctly. However, your addition of thickening the bottom grey border for the subtitle would be a framework design change, right? That one doesn't seem isolated to this use-case.

**Comment by ElementE** [comment]
@scadams - Yeah the design does have some unique styles with what I presented here. 

Im still hesitant on throwing this out to the framework until I can vette the other places this pattern will exist and then validate. 

I know this isnt optimal process, but hang in there with me!

**Comment by scadams** [comment]
FYI, we have this update in our staging environment now, with the overrides @ElementE recommended: https://staging.encore.rackspace.com/mass-ticketing/notifications

**Comment by scadams** [comment]
I'm not sure if I should close this issue or not, so I'll leave it up to @ElementE or @kobowley
